### ISSUE TITLE
Why is koa-better-body writing to ctx.body 

### ISSUE THREAD

**Issue by LaurensRietveld** [helapkg/hela#50] opened 2016-06-29 15:03 UTC
I'm confused: why is koa-better-body setting the request parameters on `ctx.body` (which is an alias to the _response_ body, according to the [docs](https://github.com/koajs/koa/blob/master/docs/api/context.md)).

As a result, whenever my middleware does not explicitly set the body, then koa-better-body does it for me. See:

``` js
var Koa = require('koa');
var body = require('koa-better-body')
var convert = require('koa-convert')
var app = new Koa();
app.use(convert(body()))
app.listen(4290, function () {
  console.log('Koa server start listening on port 4290')
  console.log('curl -i http://localhost:4290/ -F "key=val"')//should return nothing
})
```

**Comment by tunnckoCore** [comment] 2016-07-02 15:36
hm... good point, my fault ;d

**Comment by tunnckoCore** [comment] 2016-07-02 15:40
@LaurensRietveld make sense.

PR welcome to remove `ctx.body =` from lines 188, 193, 204 and 205, and change `ctx.body =` from L197 to `ctx.request.body`

**Comment by internalfx** [comment] 2016-07-06 15:35
On my project, this has the bad effect of bouncing back whatever was sent even if no matching route was found.

I made the changes locally. Unsurprisingly this breaks the tests.

```
test('should parse a json body', function (done) {
  request(app.callback())
    .post('/')
    .send({ foo: 'lol' })
    .expect(200)
    .expect({ foo: 'lol' }, done)
})
```

The json tests are currently expecting the bounced back content.

**Comment by tunnckoCore** [comment] 2016-07-07 16:59
Yea yea, I'm agree. Tests will be broken, but fix would be easy (just middleware before the koa-better-body middleware, that appends to this.body from this.request), i seen that. PRs welcome, because am in university session now and dont have any time.

**Comment by tunnckoCore** [comment] 2016-07-08 23:41
@LaurensRietveld @internalfx i think i'm going to fix that this night.

**Comment by internalfx** [comment] 2016-07-09 00:14
oh ok...I have it fixed in my fork, but I did not submit a PR because of the messed up tests

**Comment by tunnckoCore** [comment] 2016-07-09 00:28
> because of the messed up tests

yea, it's normal. just fixed them and i'll push in a bit.

**Closed as completed** 2016-07-09 00:40 UTC

**Comment by internalfx** [comment] 2016-07-09 00:45
Since this is totally a breaking change, will we see a version `3.0.0`?

**Comment by tunnckoCore** [comment] 2016-07-09 02:20
Hm. Not sure, i'm thinking for `2.1.0`, because it is fix of a bug and it's totally unexpected behavior to rely on.

Not sure, but in any way it won't be patch version. Also I got few more new ideas which will post in new issue in a bit (https://github.com/tunnckoCore/koa-better-body/issues/52), so maybe yea.
